name: Write "hello" to file

on:
  schedule:
    - cron: "*/5 * * * *"
  push:
    branches:
      - main

jobs:
  write_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run script
        run: |
          python script.py

      - name: Upload output.txt as artifact
        uses: actions/upload-artifact@v3
        with:
          name: output-file
          path: output.txt
