name: Write "hello" to file

on:
  schedule:
    - cron: "*/5 * * * *" # Ejecuta cada 5 minutos (GitHub Actions no permite cada minuto)

jobs:
  write_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run script
        run: |
          python script.py
