name: Do Scrap of the axius website

on:
  schedule:
    - cron: "0 14 * * *"
  push:
    branches:
      - main

jobs:
  write_hello:
    runs-on: ubuntu-latest

    steps:
      # Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: |
          python do_scrap.py

      # Optional: Commit and push changes
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add results/
          git add do_scrap.log
          git commit -m "Scrap done: $(date)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}